# Generated by Django 5.2.5 on 2025-09-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('experience', models.IntegerField(max_length=15)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
    ]
