# Generated by Django 5.2.5 on 2025-08-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fathername', models.CharField(max_length=50)),
                ('classname', models.IntegerField(max_length=15)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
    ]
